/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.ClientController;
import Controller.TextFileController;
import Controller.TrainerController;
import DTO.Mappers.EGender;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author auxlu
 */
public class EditTrainer extends javax.swing.JFrame {

    TrainerController trainerController = new TrainerController();
    TextFileController controller = new TextFileController();
    
    String filePath = "C:\\Users\\auxlu\\OneDrive\\Documentos\\NetBeansProjects\\ClientManagment\\src\\Resources\\trainers.txt";

    /**
     * Creates new form EditUser
     */
    public EditTrainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneEditClient = new javax.swing.JTabbedPane();
        jPanelEditClient = new javax.swing.JPanel();
        jLabelAddressContact2 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername1 = new javax.swing.JLabel();
        jLabelLastName1 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelFirstName1 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelGender1 = new javax.swing.JLabel();
        jTextFieldState = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelPassword1 = new javax.swing.JLabel();
        jFormattedBirthDate = new javax.swing.JFormattedTextField();
        jLabelInformation1 = new javax.swing.JLabel();
        jLabelBirthDate1 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabelState1 = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabelPhone1 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelCountry1 = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jTextFieldGym = new javax.swing.JTextField();
        jLabelGym = new javax.swing.JLabel();
        jLabelAddressContact3 = new javax.swing.JLabel();
        jLabelEmail3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelOccupationCPF = new javax.swing.JLabel();
        jLabelHourlyRate = new javax.swing.JLabel();
        jLabelSpeciality = new javax.swing.JLabel();
        jLabelYearsOfExperience = new javax.swing.JLabel();
        jLabelSalary = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldCertification = new javax.swing.JTextField();
        jLabelCertification = new javax.swing.JLabel();
        jFormattedTextFieldYearsOfExperience = new javax.swing.JFormattedTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jFormattedTextFieldHourlyRate = new javax.swing.JFormattedTextField();
        jButtonOpen = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldSpeciality = new javax.swing.JTextField();
        jTextFieldSalary = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneEditClient.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPaneEditClient.setPreferredSize(new java.awt.Dimension(1121, 531));

        jPanelEditClient.setPreferredSize(new java.awt.Dimension(1121, 531));
        jPanelEditClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAddressContact2.setText("Address and Contact");
        jPanelEditClient.add(jLabelAddressContact2,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jTextFieldUsername.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldUsername.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabelUsername1.setText("Username:");
        jPanelEditClient.add(jLabelUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabelLastName1.setText("laststName:");
        jPanelEditClient.add(jLabelLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jTextFieldLastName.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldLastName.setPreferredSize(new java.awt.Dimension(320, 22));
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 430, -1));

        jLabelFirstName1.setText("firstName:");
        jPanelEditClient.add(jLabelFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jTextFieldFirstName.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldFirstName.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstNameActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabelGender1.setText("Gender:");
        jPanelEditClient.add(jLabelGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        jTextFieldState.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldState.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStateActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldState, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabelEmail1.setText("City:");
        jPanelEditClient.add(jLabelEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        jLabelPassword1.setText("Password:");
        jPanelEditClient.add(jLabelPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jFormattedBirthDate.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanelEditClient.add(jFormattedBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 90, -1));

        jLabelInformation1.setText("User Information");
        jPanelEditClient.add(jLabelInformation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabelBirthDate1.setText("Birth Date:");
        jPanelEditClient.add(jLabelBirthDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jComboBoxGender
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER", " " }));
        jComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenderActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jComboBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        jLabelState1.setText("State:");
        jPanelEditClient.add(jLabelState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jTextFieldCity.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldCity.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCityActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        jLabelPhone1.setText("Phone:");
        jPanelEditClient.add(jLabelPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jTextFieldPhone.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldPhone.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabelCountry1.setText("Country:");
        jPanelEditClient.add(jLabelCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jTextFieldCountry.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldCountry.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountryActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jTextFieldGym.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldGym.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGymActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldGym, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabelGym.setText("Gym");
        jPanelEditClient.add(jLabelGym, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabelAddressContact3.setText("Trainer Info");
        jPanelEditClient.add(jLabelAddressContact3,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabelEmail3.setText("Email:");
        jPanelEditClient.add(jLabelEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jTextFieldEmail.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldEmail.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabelOccupationCPF.setText("CPF");
        jPanelEditClient.add(jLabelOccupationCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabelHourlyRate.setText("Hourly Rate: ");
        jPanelEditClient.add(jLabelHourlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jLabelSpeciality.setText("Speciality");
        jPanelEditClient.add(jLabelSpeciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabelYearsOfExperience.setText("Years of Experience:");
        jPanelEditClient.add(jLabelYearsOfExperience,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jLabelSalary.setText("Salary");
        jPanelEditClient.add(jLabelSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        jTextFieldCPF.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldCPF.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jTextFieldCertification.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldCertification.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextFieldCertification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCertificationActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jTextFieldCertification,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabelCertification.setText("Certification");
        jPanelEditClient.add(jLabelCertification, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jFormattedTextFieldYearsOfExperience.setMinimumSize(new java.awt.Dimension(100, 22));
        jFormattedTextFieldYearsOfExperience.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanelEditClient.add(jFormattedTextFieldYearsOfExperience,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jPasswordField.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanelEditClient.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jFormattedTextFieldHourlyRate.setMinimumSize(new java.awt.Dimension(100, 22));
        jFormattedTextFieldHourlyRate.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanelEditClient.add(jFormattedTextFieldHourlyRate,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jButtonOpen.setText("Open");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jButtonOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 50));

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 150, 50));

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 150, 50));
        jPanelEditClient.add(jTextFieldSpeciality,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 100, -1));

        jTextFieldSalary.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextFieldSalary.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanelEditClient.add(jTextFieldSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanelEditClient.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 150, 50));

        jTabbedPaneEditClient.addTab("Edit Trainer", jPanelEditClient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPaneEditClient, javax.swing.GroupLayout.DEFAULT_SIZE, 1065,
                                        Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPaneEditClient, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegisterActionPerformed
        String CPF = "811";
        String username = jTextFieldUsername.getText();
        String firstName = jTextFieldFirstName.getText();
        String lastName = jTextFieldLastName.getText();
        String email = jTextFieldEmail.getText();
        String password = jPasswordField.getSelectedText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd");
        LocalDate birthDate = LocalDate.parse(jFormattedBirthDate.getText(), formatter);
        EGender gender = EGender.valueOf(jComboBoxGender.getSelectedItem().toString());
        String phoneNumber = jTextFieldPhone.getText();
        String city = jTextFieldCity.getText();
        String state = jTextFieldState.getText();
        String country = jTextFieldCountry.getText();
        String gym = jTextFieldGym.getText();
        String certification = jTextFieldCertification.getText();
        String speciality = jTextFieldSpeciality.getText();
        int yearsOfExperience = Integer.parseInt(jFormattedTextFieldYearsOfExperience.getText());
        double hourlyRate = Double.parseDouble(jFormattedTextFieldHourlyRate.getText());
        double salary = Double.parseDouble(jTextFieldSalary.getText());

        String trainerInfo = String.format("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
                CPF, username, firstName, lastName, email, password, phoneNumber, birthDate, gender,
                city, state, country, gym, certification, speciality, yearsOfExperience, hourlyRate, salary);
        // String content = header + clientInfo;
        String content = trainerInfo;
        controller.setArchive("Salvar");
        controller.setText(content);
        if (controller.write(false)) {
            JOptionPane.showMessageDialog(this,
                    "Trainer registered successfully",
                    "Archive registered",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Archive not registered",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        }

    }// GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDeleteActionPerformed
    // replace with your file path
    boolean deleted = controller.delete(filePath);
    
    if (deleted) {
        JOptionPane.showMessageDialog(this,
                "Archive deleted successfully",
                "Archive deleted",
                JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this,
                "Archive not deleted",
                "Error",
                JOptionPane.WARNING_MESSAGE);
    }
    }// GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonUpdateActionPerformed
        String CPF = "811";
        String username = jTextFieldUsername.getText();
        String firstName = jTextFieldFirstName.getText();
        String lastName = jTextFieldLastName.getText();
        String email = jTextFieldEmail.getText();
        String password = jPasswordField.getSelectedText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd");
        LocalDate birthDate = LocalDate.parse(jFormattedBirthDate.getText(), formatter);
        EGender gender = EGender.valueOf(jComboBoxGender.getSelectedItem().toString());
        String phoneNumber = jTextFieldPhone.getText();
        String city = jTextFieldCity.getText();
        String state = jTextFieldState.getText();
        String country = jTextFieldCountry.getText();
        String gym = jTextFieldGym.getText();
        String certification = jTextFieldCertification.getText();
        String speciality = jTextFieldSpeciality.getText();
        int yearsOfExperience = Integer.parseInt(jFormattedTextFieldYearsOfExperience.getText());
        double hourlyRate = Double.parseDouble(jFormattedTextFieldHourlyRate.getText());
        double salary = Double.parseDouble(jTextFieldSalary.getText());

        String trainerInfo = String.format("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
                CPF, username, firstName, lastName, email, password, phoneNumber, birthDate, gender,
                city, state, country, gym, certification, speciality, yearsOfExperience, hourlyRate, salary);

        

        
        if (controller.update(filePath, trainerInfo)) {
            JOptionPane.showMessageDialog(this,
                    "Trainer " + firstName + " " + lastName + "updated successfully",
                    "Archive updated",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Archive not updated",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        }
    }// GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOpenActionPerformed
        controller.setArchive("Abrir");
        StringBuilder sb = new StringBuilder();
        if (controller.read()) {

            String line = controller.getText();
            for (String value : line.split("\n")) {
                sb.append(value);
            }

            // process fileContent as needed
        }
        String[] values = sb.toString().split(",");
        jTextFieldUsername.setText(values[1]);
        jTextFieldFirstName.setText(values[2]);
        jTextFieldLastName.setText(values[3]);
        jTextFieldEmail.setText(values[4]);
        jPasswordField.setText(values[5]);
        jTextFieldPhone.setText(values[6]);
        jFormattedBirthDate.setText(values[7]);
        jComboBoxGender.setSelectedItem(values[8]);
        jTextFieldCity.setText(values[9]);
        jTextFieldState.setText(values[10]);
        jTextFieldCountry.setText(values[11]);
        jTextFieldGym.setText(values[12]);
        jTextFieldCertification.setText(values[13]);
        jTextFieldSpeciality.setText(values[14]);
        jFormattedTextFieldYearsOfExperience.setText(values[15]);
        jFormattedTextFieldHourlyRate.setText(values[16]);
        jTextFieldSalary.setText(values[17]);

        if (controller.read()) {
            JOptionPane.showMessageDialog(this,
                    "Archive opened successfully",
                    "Archive opened",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Archive not opened",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        }
    }// GEN-LAST:event_jButtonOpenActionPerformed

    private void jTextFieldCertificationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCertificationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCertificationActionPerformed

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldGymActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldGymActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldGymActionPerformed

    private void jTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCountryActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCountryActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCityActionPerformed

    private void jComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxGenderActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBoxGenderActionPerformed

    private void jTextFieldStateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldStateActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldStateActionPerformed

    private void jTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldFirstNameActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldIncomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldIncomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldIncomeActionPerformed

    private void jTextFieldOccupationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldOccupationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldOccupationActionPerformed

    private void jTextFieldCardHolderNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCardHolderNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCardHolderNameActionPerformed

    private void jTextFieldUsername1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldUsername1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldUsername1ActionPerformed

    private void jTextFieldLastName1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLastName1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldLastName1ActionPerformed

    private void jTextFieldFirstName1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldFirstName1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldFirstName1ActionPerformed

    private void jTextFieldState1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldState1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldState1ActionPerformed

    private void jComboBoxGender1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxGender1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBoxGender1ActionPerformed

    private void jTextFieldCity1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCity1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCity1ActionPerformed

    private void jTextFieldPhone1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldPhone1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldPhone1ActionPerformed

    private void jTextFieldCountry1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCountry1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCountry1ActionPerformed

    private void jTextFieldIncome1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldIncome1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldIncome1ActionPerformed

    private void jTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldEmail1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldEmail1ActionPerformed

    private void jTextFieldOccupation1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldOccupation1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldOccupation1ActionPerformed

    private void jTextFieldCardHolderName1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCardHolderName1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCardHolderName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JFormattedTextField jFormattedBirthDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldHourlyRate;
    private javax.swing.JFormattedTextField jFormattedTextFieldYearsOfExperience;
    private javax.swing.JLabel jLabelAddressContact2;
    private javax.swing.JLabel jLabelAddressContact3;
    private javax.swing.JLabel jLabelBirthDate1;
    private javax.swing.JLabel jLabelCertification;
    private javax.swing.JLabel jLabelCountry1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelEmail3;
    private javax.swing.JLabel jLabelFirstName1;
    private javax.swing.JLabel jLabelGender1;
    private javax.swing.JLabel jLabelGym;
    private javax.swing.JLabel jLabelHourlyRate;
    private javax.swing.JLabel jLabelInformation1;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelOccupationCPF;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelPhone1;
    private javax.swing.JLabel jLabelSalary;
    private javax.swing.JLabel jLabelSpeciality;
    private javax.swing.JLabel jLabelState1;
    private javax.swing.JLabel jLabelUsername1;
    private javax.swing.JLabel jLabelYearsOfExperience;
    private javax.swing.JPanel jPanelEditClient;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTabbedPane jTabbedPaneEditClient;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCertification;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldGym;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSalary;
    private javax.swing.JTextField jTextFieldSpeciality;
    private javax.swing.JTextField jTextFieldState;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
