/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.ClientController;
import DTO.Mappers.EGender;
import Model.Client;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import Controller.TextFileController;
import javax.swing.JFrame;

/**
 *
 * @author auxlu
 */
public class Register extends javax.swing.JFrame {

    ClientController clientController = new ClientController();
    TextFileController controller = new TextFileController();

    /**
     * Creates new form ClientManagment
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneManagerUsers = new javax.swing.JTabbedPane();
        jPanelManagerUsers = new javax.swing.JPanel();
        jButtonClient = new javax.swing.JButton();
        jButtonManager = new javax.swing.JButton();
        jButtonTrainer = new javax.swing.JButton();
        jPaneUserDetails = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaClientDetails = new javax.swing.JTextArea();
        jButtonOpenClientDetails = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemEditClient = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 720));

        jTabbedPaneManagerUsers.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanelManagerUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClient.setText("Client");
        jButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientActionPerformed(evt);
            }
        });
        jPanelManagerUsers.add(jButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 80));

        jButtonManager.setText("Manager");
        jButtonManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerActionPerformed(evt);
            }
        });
        jPanelManagerUsers.add(jButtonManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 150, 80));

        jButtonTrainer.setText("Trainer");
        jButtonTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrainerActionPerformed(evt);
            }
        });
        jPanelManagerUsers.add(jButtonTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 150, 80));

        jTabbedPaneManagerUsers.addTab("Manager Users", jPanelManagerUsers);

        jTextAreaClientDetails.setColumns(20);
        jTextAreaClientDetails.setRows(5);
        jScrollPane2.setViewportView(jTextAreaClientDetails);

        jButtonOpenClientDetails.setText("Open");
        jButtonOpenClientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenClientDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneUserDetailsLayout = new javax.swing.GroupLayout(jPaneUserDetails);
        jPaneUserDetails.setLayout(jPaneUserDetailsLayout);
        jPaneUserDetailsLayout.setHorizontalGroup(
            jPaneUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneUserDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPaneUserDetailsLayout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jButtonOpenClientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jPaneUserDetailsLayout.setVerticalGroup(
            jPaneUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneUserDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOpenClientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        jTabbedPaneManagerUsers.addTab("User Details", jPaneUserDetails);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemEditClient.setText("EditClients");
        jMenuItemEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditClientActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemEditClient);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneManagerUsers)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneManagerUsers)
        );

        setSize(new java.awt.Dimension(1135, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEditClientActionPerformed

    private void jButtonOpenClientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenClientDetailsActionPerformed
       controller.setArchive("Abrir");
        if (controller.read()) {
            jTextAreaClientDetails.setText(controller.getText());
        }
    }//GEN-LAST:event_jButtonOpenClientDetailsActionPerformed

    private void jButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientActionPerformed
        EditClient editClient = new EditClient();
        editClient.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        editClient.setLocationRelativeTo(this); // center the window in the main JFrame
        editClient.setVisible(true);
    }//GEN-LAST:event_jButtonClientActionPerformed

    private void jButtonManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerActionPerformed
        EditManager editManager = new EditManager();
        editManager.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        editManager.setLocationRelativeTo(this); // center the window in the main JFrame
        editManager.setVisible(true);
    }//GEN-LAST:event_jButtonManagerActionPerformed

    private void jButtonTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrainerActionPerformed
        EditTrainer editTrainer = new EditTrainer();
        editTrainer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        editTrainer.setLocationRelativeTo(this); // center the window in the main JFrame
        editTrainer.setVisible(true);
    }//GEN-LAST:event_jButtonTrainerActionPerformed

    

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldFirstNameActionPerformed

    private void jTextFieldStateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldStateActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldStateActionPerformed

    private void jComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxGenderActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBoxGenderActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCityActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldPhone1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldPhone1ActionPerformed

    private void jTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCountryActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCountryActionPerformed

    private void jTextFieldIncomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldIncomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldIncomeActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldOccupationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldOccupationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldOccupationActionPerformed

    private void jTextFieldCardHolderNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCardHolderNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldCardHolderNameActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClient;
    private javax.swing.JButton jButtonManager;
    private javax.swing.JButton jButtonOpenClientDetails;
    private javax.swing.JButton jButtonTrainer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemEditClient;
    private javax.swing.JPanel jPaneUserDetails;
    private javax.swing.JPanel jPanelManagerUsers;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneManagerUsers;
    private javax.swing.JTextArea jTextAreaClientDetails;
    // End of variables declaration//GEN-END:variables
}
